apiVersion: v1
kind: Secret
metadata:
  name: laravel-db
  namespace: prod
type: Opaque
stringData:
  username: "laravel"
  password: "password"
---  
apiVersion: v1
kind: Secret
metadata:
  name: cpm-main-app
  namespace: prod
type: Opaque
stringData:
  APP_KEY: "base64:eQrCXchv9wpGiOqRFaeIGPnqklzvU+A6CZYSMosh1to="
  FCM_KEY: ""
  DB_USERNAME: "laravel"
  DB_PASSWORD: "password"
  REDIS_PASSWORD: "password"
  MAIL_USERNAME: "noreply@example.com"
  MAIL_PASSWORD: "password"