# This workflow is provided for build and push image
name: ci

on:
  push:  
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  #BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  BUILDKIT_IMAGE: jkaninda/laravel-kubernetes-example-app
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set environment for branch
        run: |
          set -x
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "TAG_NAME=latest" >> "$GITHUB_ENV"
            echo "runs-on: master branch"
          else
            echo "TAG_NAME=${{ github.head_ref || github.ref_name }}" >> "$GITHUB_ENV"
            echo "runs-on: ${{ github.head_ref || github.ref_name }} branch"
          fi
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./docker/Dockerfile
          push: true
          tags: "${{env.BUILDKIT_IMAGE}}:${{env.TAG_NAME}}"